// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (game_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, game_id, sender_id, content, created_at
`

type CreateChatMessageParams struct {
	GameID   pgtype.UUID `json:"game_id"`
	SenderID pgtype.UUID `json:"sender_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage, arg.GameID, arg.SenderID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatMessagesByGameID = `-- name: DeleteChatMessagesByGameID :exec
DELETE FROM chat_messages
WHERE game_id = $1
`

func (q *Queries) DeleteChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatMessagesByGameID, gameID)
	return err
}

const getChatMessagesByGameID = `-- name: GetChatMessagesByGameID :many
SELECT id, game_id, sender_id, content, created_at FROM chat_messages
WHERE game_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesByGameIDPaginated = `-- name: GetChatMessagesByGameIDPaginated :many
SELECT id, game_id, sender_id, content, created_at FROM chat_messages
WHERE game_id = $1
  AND created_at < $2::timestamptz
ORDER BY created_at DESC
LIMIT $3::int
`

type GetChatMessagesByGameIDPaginatedParams struct {
	GameID   pgtype.UUID        `json:"game_id"`
	Before   pgtype.Timestamptz `json:"before"`
	PageSize int32              `json:"page_size"`
}

func (q *Queries) GetChatMessagesByGameIDPaginated(ctx context.Context, arg GetChatMessagesByGameIDPaginatedParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesByGameIDPaginated, arg.GameID, arg.Before, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
