// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_otps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentOTPsForUser = `-- name: CountRecentOTPsForUser :one
SELECT COUNT(*) FROM email_otps
WHERE user_id    = $1
  AND created_at > NOW() - INTERVAL '5 minutes'
`

// Rate-limit OTP generation: reject if a code was issued in the last 5 minutes.
func (q *Queries) CountRecentOTPsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailOTP = `-- name: CreateEmailOTP :one
INSERT INTO email_otps (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, code_hash, expires_at, attempts, used_at, created_at
`

type CreateEmailOTPParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, createEmailOTP, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM email_otps
WHERE expires_at < NOW()
`

// Run periodically (e.g. a cron job) to keep the table small.
func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getValidOTP = `-- name: GetValidOTP :one
SELECT id, user_id, code_hash, expires_at, attempts, used_at, created_at FROM email_otps
WHERE user_id  = $1
  AND expires_at > NOW()
  AND used_at  IS NULL
  AND attempts < 5
ORDER BY created_at DESC
LIMIT 1
`

// Returns the most-recent, unexpired, unused code that still has attempts left.
// The app layer must hash the user-supplied digit string before comparing code_hash.
func (q *Queries) GetValidOTP(ctx context.Context, userID pgtype.UUID) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, getValidOTP, userID)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE email_otps
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, user_id, code_hash, expires_at, attempts, used_at, created_at
`

// Call this on every failed verification attempt.
func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserOTPs = `-- name: InvalidateUserOTPs :exec
UPDATE email_otps
SET used_at = NOW()
WHERE user_id = $1
  AND used_at IS NULL
`

// Burn all live codes for a user before issuing a new one.
func (q *Queries) InvalidateUserOTPs(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateUserOTPs, userID)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :one
UPDATE email_otps
SET used_at = NOW()
WHERE id      = $1
  AND used_at IS NULL
RETURNING id, user_id, code_hash, expires_at, attempts, used_at, created_at
`

// Call this immediately after a successful match to prevent replay.
func (q *Queries) MarkOTPUsed(ctx context.Context, id pgtype.UUID) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, markOTPUsed, id)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
