// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameAsBlack = `-- name: CreateGameAsBlack :one
INSERT INTO games (black_player_id, visibility, board_state, white_time_remaining_ms, black_time_remaining_ms, opponent, stockfish_level, state, last_move_at)
VALUES ($1, $2, $3, $4, $4, $5, $6, $7, NOW())
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level
`

type CreateGameAsBlackParams struct {
	BlackPlayerID        pgtype.UUID `json:"black_player_id"`
	Visibility           string      `json:"visibility"`
	BoardState           string      `json:"board_state"`
	WhiteTimeRemainingMs int64       `json:"white_time_remaining_ms"`
	Opponent             string      `json:"opponent"`
	StockfishLevel       int16       `json:"stockfish_level"`
	State                GameState   `json:"state"`
}

func (q *Queries) CreateGameAsBlack(ctx context.Context, arg CreateGameAsBlackParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsBlack,
		arg.BlackPlayerID,
		arg.Visibility,
		arg.BoardState,
		arg.WhiteTimeRemainingMs,
		arg.Opponent,
		arg.StockfishLevel,
		arg.State,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}

const createGameAsWhite = `-- name: CreateGameAsWhite :one
INSERT INTO games (white_player_id, visibility, board_state, white_time_remaining_ms, black_time_remaining_ms, opponent, stockfish_level, state, last_move_at)
VALUES ($1, $2, $3, $4, $4, $5, $6, $7, NOW())
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level
`

type CreateGameAsWhiteParams struct {
	WhitePlayerID        pgtype.UUID `json:"white_player_id"`
	Visibility           string      `json:"visibility"`
	BoardState           string      `json:"board_state"`
	WhiteTimeRemainingMs int64       `json:"white_time_remaining_ms"`
	Opponent             string      `json:"opponent"`
	StockfishLevel       int16       `json:"stockfish_level"`
	State                GameState   `json:"state"`
}

func (q *Queries) CreateGameAsWhite(ctx context.Context, arg CreateGameAsWhiteParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsWhite,
		arg.WhitePlayerID,
		arg.Visibility,
		arg.BoardState,
		arg.WhiteTimeRemainingMs,
		arg.Opponent,
		arg.StockfishLevel,
		arg.State,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getActiveGamesByUser = `-- name: GetActiveGamesByUser :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level FROM games 
WHERE (white_player_id = $1 OR black_player_id = $1)
AND state IN ('waiting', 'active')
`

func (q *Queries) GetActiveGamesByUser(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getActiveGamesByUser, whitePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
			&i.Opponent,
			&i.StockfishLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}

const getGamesByPlayerID = `-- name: GetGamesByPlayerID :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level FROM games
WHERE white_player_id = $1
   OR black_player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGamesByPlayerID(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByPlayerID, whitePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
			&i.Opponent,
			&i.StockfishLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinGameAsBlack = `-- name: JoinGameAsBlack :one
UPDATE games
SET
    black_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND black_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level
`

type JoinGameAsBlackParams struct {
	ID            pgtype.UUID `json:"id"`
	BlackPlayerID pgtype.UUID `json:"black_player_id"`
}

func (q *Queries) JoinGameAsBlack(ctx context.Context, arg JoinGameAsBlackParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsBlack, arg.ID, arg.BlackPlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}

const joinGameAsWhite = `-- name: JoinGameAsWhite :one
UPDATE games
SET
    white_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND white_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level
`

type JoinGameAsWhiteParams struct {
	ID            pgtype.UUID `json:"id"`
	WhitePlayerID pgtype.UUID `json:"white_player_id"`
}

func (q *Queries) JoinGameAsWhite(ctx context.Context, arg JoinGameAsWhiteParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsWhite, arg.ID, arg.WhitePlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}

const listLiveGames = `-- name: ListLiveGames :many
SELECT g.id, g.move_count, g.current_player,
       g.white_time_remaining_ms, g.black_time_remaining_ms,
       g.created_at, g.updated_at,
       wu.username AS white_username, wu.rating AS white_rating,
       bu.username AS black_username, bu.rating AS black_rating
FROM games g
JOIN users wu ON wu.id = g.white_player_id
JOIN users bu ON bu.id = g.black_player_id
WHERE g.state = 'active' AND g.visibility = 'public' AND g.opponent = 'person'
ORDER BY g.updated_at DESC
LIMIT 50
`

type ListLiveGamesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	MoveCount            int32              `json:"move_count"`
	CurrentPlayer        PlayerColor        `json:"current_player"`
	WhiteTimeRemainingMs int64              `json:"white_time_remaining_ms"`
	BlackTimeRemainingMs int64              `json:"black_time_remaining_ms"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	WhiteUsername        string             `json:"white_username"`
	WhiteRating          int32              `json:"white_rating"`
	BlackUsername        string             `json:"black_username"`
	BlackRating          int32              `json:"black_rating"`
}

func (q *Queries) ListLiveGames(ctx context.Context) ([]ListLiveGamesRow, error) {
	rows, err := q.db.Query(ctx, listLiveGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveGamesRow{}
	for rows.Next() {
		var i ListLiveGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.MoveCount,
			&i.CurrentPlayer,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WhiteUsername,
			&i.WhiteRating,
			&i.BlackUsername,
			&i.BlackRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGames = `-- name: ListPublicGames :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level FROM games
WHERE state = 'waiting' AND visibility = 'public' AND opponent = 'person'
ORDER BY created_at ASC
`

func (q *Queries) ListPublicGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listPublicGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
			&i.Opponent,
			&i.StockfishLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingGames = `-- name: ListWaitingGames :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level FROM games
WHERE state = 'waiting' AND opponent = 'person'
ORDER BY created_at ASC
`

func (q *Queries) ListWaitingGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listWaitingGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
			&i.Opponent,
			&i.StockfishLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET
    state                  = $2,
    in_check               = $3,
    current_player         = $4,
    move_count             = $5,
    board_state            = $6,
    white_time_remaining_ms = $7,
    black_time_remaining_ms = $8,
    ended_by_player_id     = $9,
    end_reason             = $10,
    last_move_at           = $11,
    updated_at             = NOW()
WHERE id = $1
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility, opponent, stockfish_level
`

type UpdateGameStateParams struct {
	ID                   pgtype.UUID        `json:"id"`
	State                GameState          `json:"state"`
	InCheck              bool               `json:"in_check"`
	CurrentPlayer        PlayerColor        `json:"current_player"`
	MoveCount            int32              `json:"move_count"`
	BoardState           string             `json:"board_state"`
	WhiteTimeRemainingMs int64              `json:"white_time_remaining_ms"`
	BlackTimeRemainingMs int64              `json:"black_time_remaining_ms"`
	EndedByPlayerID      pgtype.UUID        `json:"ended_by_player_id"`
	EndReason            string             `json:"end_reason"`
	LastMoveAt           pgtype.Timestamptz `json:"last_move_at"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState,
		arg.ID,
		arg.State,
		arg.InCheck,
		arg.CurrentPlayer,
		arg.MoveCount,
		arg.BoardState,
		arg.WhiteTimeRemainingMs,
		arg.BlackTimeRemainingMs,
		arg.EndedByPlayerID,
		arg.EndReason,
		arg.LastMoveAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
		&i.Opponent,
		&i.StockfishLevel,
	)
	return i, err
}
