// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameAsBlack = `-- name: CreateGameAsBlack :one
INSERT INTO games (black_player_id)
VALUES ($1)
RETURNING id, white_player_id, black_player_id, state, in_check, created_at, updated_at
`

func (q *Queries) CreateGameAsBlack(ctx context.Context, blackPlayerID pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsBlack, blackPlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGameAsWhite = `-- name: CreateGameAsWhite :one
INSERT INTO games (white_player_id)
VALUES ($1)
RETURNING id, white_player_id, black_player_id, state, in_check, created_at, updated_at
`

func (q *Queries) CreateGameAsWhite(ctx context.Context, whitePlayerID pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsWhite, whitePlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, white_player_id, black_player_id, state, in_check, created_at, updated_at FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGamesByPlayerID = `-- name: GetGamesByPlayerID :many
SELECT id, white_player_id, black_player_id, state, in_check, created_at, updated_at FROM games
WHERE white_player_id = $1
   OR black_player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGamesByPlayerID(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByPlayerID, whitePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinGameAsBlack = `-- name: JoinGameAsBlack :one
UPDATE games
SET
    black_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND black_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, created_at, updated_at
`

type JoinGameAsBlackParams struct {
	ID            pgtype.UUID `json:"id"`
	BlackPlayerID pgtype.UUID `json:"black_player_id"`
}

func (q *Queries) JoinGameAsBlack(ctx context.Context, arg JoinGameAsBlackParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsBlack, arg.ID, arg.BlackPlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const joinGameAsWhite = `-- name: JoinGameAsWhite :one
UPDATE games
SET
    white_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND white_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, created_at, updated_at
`

type JoinGameAsWhiteParams struct {
	ID            pgtype.UUID `json:"id"`
	WhitePlayerID pgtype.UUID `json:"white_player_id"`
}

func (q *Queries) JoinGameAsWhite(ctx context.Context, arg JoinGameAsWhiteParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsWhite, arg.ID, arg.WhitePlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWaitingGames = `-- name: ListWaitingGames :many
SELECT id, white_player_id, black_player_id, state, in_check, created_at, updated_at FROM games
WHERE state = 'waiting'
ORDER BY created_at ASC
`

func (q *Queries) ListWaitingGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listWaitingGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET
    state      = $2,
    in_check   = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, white_player_id, black_player_id, state, in_check, created_at, updated_at
`

type UpdateGameStateParams struct {
	ID      pgtype.UUID `json:"id"`
	State   GameState   `json:"state"`
	InCheck bool        `json:"in_check"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState, arg.ID, arg.State, arg.InCheck)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
