// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameAsBlack = `-- name: CreateGameAsBlack :one
INSERT INTO games (black_player_id)
VALUES ($1)
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility
`

func (q *Queries) CreateGameAsBlack(ctx context.Context, blackPlayerID pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsBlack, blackPlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}

const createGameAsWhite = `-- name: CreateGameAsWhite :one
INSERT INTO games (white_player_id)
VALUES ($1)
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility
`

func (q *Queries) CreateGameAsWhite(ctx context.Context, whitePlayerID pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, createGameAsWhite, whitePlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games
WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getActiveGamesByUser = `-- name: GetActiveGamesByUser :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility FROM games 
WHERE (white_player_id = $1 OR black_player_id = $1)
AND state IN ('waiting', 'active')
`

func (q *Queries) GetActiveGamesByUser(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getActiveGamesByUser, whitePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameByID = `-- name: GetGameByID :one
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility FROM games
WHERE id = $1
`

func (q *Queries) GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}

const getGamesByPlayerID = `-- name: GetGamesByPlayerID :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility FROM games
WHERE white_player_id = $1
   OR black_player_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGamesByPlayerID(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByPlayerID, whitePlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinGameAsBlack = `-- name: JoinGameAsBlack :one
UPDATE games
SET
    black_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND black_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility
`

type JoinGameAsBlackParams struct {
	ID            pgtype.UUID `json:"id"`
	BlackPlayerID pgtype.UUID `json:"black_player_id"`
}

func (q *Queries) JoinGameAsBlack(ctx context.Context, arg JoinGameAsBlackParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsBlack, arg.ID, arg.BlackPlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}

const joinGameAsWhite = `-- name: JoinGameAsWhite :one
UPDATE games
SET
    white_player_id = $2,
    state           = 'active',
    updated_at      = NOW()
WHERE id = $1
  AND state = 'waiting'
  AND white_player_id IS NULL
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility
`

type JoinGameAsWhiteParams struct {
	ID            pgtype.UUID `json:"id"`
	WhitePlayerID pgtype.UUID `json:"white_player_id"`
}

func (q *Queries) JoinGameAsWhite(ctx context.Context, arg JoinGameAsWhiteParams) (Game, error) {
	row := q.db.QueryRow(ctx, joinGameAsWhite, arg.ID, arg.WhitePlayerID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}

const listPublicGames = `-- name: ListPublicGames :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility FROM games
WHERE state = 'waiting' AND visibility = 'public'
ORDER BY created_at ASC
`

func (q *Queries) ListPublicGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listPublicGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingGames = `-- name: ListWaitingGames :many
SELECT id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility FROM games
WHERE state = 'waiting'
ORDER BY created_at ASC
`

func (q *Queries) ListWaitingGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listWaitingGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.WhitePlayerID,
			&i.BlackPlayerID,
			&i.State,
			&i.InCheck,
			&i.CurrentPlayer,
			&i.MoveCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardState,
			&i.WhiteTimeRemainingMs,
			&i.BlackTimeRemainingMs,
			&i.LastMoveAt,
			&i.EndedByPlayerID,
			&i.EndReason,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET
    state                  = $2,
    in_check               = $3,
    current_player         = $4,
    move_count             = $5,
    board_state            = $6,
    white_time_remaining_ms = $7,
    black_time_remaining_ms = $8,
    ended_by_player_id     = $9,
    end_reason             = $10,
    last_move_at           = $11,
    updated_at             = NOW()
WHERE id = $1
RETURNING id, white_player_id, black_player_id, state, in_check, current_player, move_count, created_at, updated_at, board_state, white_time_remaining_ms, black_time_remaining_ms, last_move_at, ended_by_player_id, end_reason, visibility
`

type UpdateGameStateParams struct {
	ID                   pgtype.UUID        `json:"id"`
	State                GameState          `json:"state"`
	InCheck              bool               `json:"in_check"`
	CurrentPlayer        PlayerColor        `json:"current_player"`
	MoveCount            int32              `json:"move_count"`
	BoardState           string             `json:"board_state"`
	WhiteTimeRemainingMs int64              `json:"white_time_remaining_ms"`
	BlackTimeRemainingMs int64              `json:"black_time_remaining_ms"`
	EndedByPlayerID      pgtype.UUID        `json:"ended_by_player_id"`
	EndReason            string             `json:"end_reason"`
	LastMoveAt           pgtype.Timestamptz `json:"last_move_at"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState,
		arg.ID,
		arg.State,
		arg.InCheck,
		arg.CurrentPlayer,
		arg.MoveCount,
		arg.BoardState,
		arg.WhiteTimeRemainingMs,
		arg.BlackTimeRemainingMs,
		arg.EndedByPlayerID,
		arg.EndReason,
		arg.LastMoveAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.WhitePlayerID,
		&i.BlackPlayerID,
		&i.State,
		&i.InCheck,
		&i.CurrentPlayer,
		&i.MoveCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardState,
		&i.WhiteTimeRemainingMs,
		&i.BlackTimeRemainingMs,
		&i.LastMoveAt,
		&i.EndedByPlayerID,
		&i.EndReason,
		&i.Visibility,
	)
	return i, err
}
