// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GameState string

const (
	GameStateWaiting   GameState = "waiting"
	GameStateActive    GameState = "active"
	GameStateCheckmate GameState = "checkmate"
	GameStateStalemate GameState = "stalemate"
	GameStateResign    GameState = "resign"
	GameStateDraw      GameState = "draw"
	GameStateAbandoned GameState = "abandoned"
)

func (e *GameState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameState(s)
	case string:
		*e = GameState(s)
	default:
		return fmt.Errorf("unsupported scan type for GameState: %T", src)
	}
	return nil
}

type NullGameState struct {
	GameState GameState `json:"game_state"`
	Valid     bool      `json:"valid"` // Valid is true if GameState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameState) Scan(value interface{}) error {
	if value == nil {
		ns.GameState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameState), nil
}

type PlayerColor string

const (
	PlayerColorW PlayerColor = "w"
	PlayerColorB PlayerColor = "b"
)

func (e *PlayerColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerColor(s)
	case string:
		*e = PlayerColor(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerColor: %T", src)
	}
	return nil
}

type NullPlayerColor struct {
	PlayerColor PlayerColor `json:"player_color"`
	Valid       bool        `json:"valid"` // Valid is true if PlayerColor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerColor) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerColor), nil
}

type VoiceSessionState string

const (
	VoiceSessionStatePending VoiceSessionState = "pending"
	VoiceSessionStateActive  VoiceSessionState = "active"
	VoiceSessionStateEnded   VoiceSessionState = "ended"
)

func (e *VoiceSessionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoiceSessionState(s)
	case string:
		*e = VoiceSessionState(s)
	default:
		return fmt.Errorf("unsupported scan type for VoiceSessionState: %T", src)
	}
	return nil
}

type NullVoiceSessionState struct {
	VoiceSessionState VoiceSessionState `json:"voice_session_state"`
	Valid             bool              `json:"valid"` // Valid is true if VoiceSessionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoiceSessionState) Scan(value interface{}) error {
	if value == nil {
		ns.VoiceSessionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoiceSessionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoiceSessionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoiceSessionState), nil
}

type ChatMessage struct {
	ID        pgtype.UUID        `json:"id"`
	GameID    pgtype.UUID        `json:"game_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailOtp struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int16              `json:"attempts"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID            pgtype.UUID        `json:"id"`
	WhitePlayerID pgtype.UUID        `json:"white_player_id"`
	BlackPlayerID pgtype.UUID        `json:"black_player_id"`
	State         GameState          `json:"state"`
	InCheck       bool               `json:"in_check"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GameMove struct {
	ID           pgtype.UUID        `json:"id"`
	GameID       pgtype.UUID        `json:"game_id"`
	PlayerID     pgtype.UUID        `json:"player_id"`
	PlayerColor  PlayerColor        `json:"player_color"`
	MoveNotation string             `json:"move_notation"`
	MoveNumber   int32              `json:"move_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	EmailConfirmed bool               `json:"email_confirmed"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
	IsActive       bool               `json:"is_active"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VoiceSession struct {
	ID          pgtype.UUID        `json:"id"`
	GameID      pgtype.UUID        `json:"game_id"`
	InitiatorID pgtype.UUID        `json:"initiator_id"`
	State       VoiceSessionState  `json:"state"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	EndedAt     pgtype.Timestamptz `json:"ended_at"`
}
