// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscriptionByUser = `-- name: DeletePushSubscriptionByUser :exec
DELETE FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) DeletePushSubscriptionByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByUser, userID)
	return err
}

const getPushSubscriptionByUser = `-- name: GetPushSubscriptionByUser :one
SELECT endpoint, p256dh, auth
FROM push_subscriptions
WHERE user_id = $1
`

type GetPushSubscriptionByUserRow struct {
	Endpoint string `json:"endpoint"`
	P256dh   string `json:"p256dh"`
	Auth     string `json:"auth"`
}

func (q *Queries) GetPushSubscriptionByUser(ctx context.Context, userID pgtype.UUID) (GetPushSubscriptionByUserRow, error) {
	row := q.db.QueryRow(ctx, getPushSubscriptionByUser, userID)
	var i GetPushSubscriptionByUserRow
	err := row.Scan(&i.Endpoint, &i.P256dh, &i.Auth)
	return i, err
}

const getPushSubscriptionExists = `-- name: GetPushSubscriptionExists :one
SELECT id FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptionExists(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPushSubscriptionExists, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const savePushSubscription = `-- name: SavePushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET endpoint = EXCLUDED.endpoint,
    p256dh   = EXCLUDED.p256dh,
    auth     = EXCLUDED.auth
`

type SavePushSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
	P256dh   string      `json:"p256dh"`
	Auth     string      `json:"auth"`
}

func (q *Queries) SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, savePushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
