// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateVoiceSession(ctx context.Context, id pgtype.UUID) (VoiceSession, error)
	CountMovesByGameID(ctx context.Context, gameID pgtype.UUID) (int64, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateGame(ctx context.Context, whitePlayerID pgtype.UUID) (Game, error)
	CreateMove(ctx context.Context, arg CreateMoveParams) (GameMove, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error)
	DeleteChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) error
	DeleteGame(ctx context.Context, id pgtype.UUID) error
	DeleteMovesByGameID(ctx context.Context, gameID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	EndVoiceSession(ctx context.Context, id pgtype.UUID) (VoiceSession, error)
	GetActiveVoiceSessionByGameID(ctx context.Context, gameID pgtype.UUID) (VoiceSession, error)
	GetChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) ([]ChatMessage, error)
	GetChatMessagesByGameIDPaginated(ctx context.Context, arg GetChatMessagesByGameIDPaginatedParams) ([]ChatMessage, error)
	GetGameByID(ctx context.Context, id pgtype.UUID) (Game, error)
	GetGamesByPlayerID(ctx context.Context, whitePlayerID pgtype.UUID) ([]Game, error)
	GetLastMoveByGameID(ctx context.Context, gameID pgtype.UUID) (GameMove, error)
	GetMovesByGameID(ctx context.Context, gameID pgtype.UUID) ([]GameMove, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVoiceSessionByID(ctx context.Context, id pgtype.UUID) (VoiceSession, error)
	GetVoiceSessionsByGameID(ctx context.Context, gameID pgtype.UUID) ([]VoiceSession, error)
	JoinGame(ctx context.Context, arg JoinGameParams) (Game, error)
	ListWaitingGames(ctx context.Context) ([]Game, error)
	UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
