// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateVoiceSession = `-- name: ActivateVoiceSession :one
UPDATE voice_sessions
SET state = 'active'
WHERE id = $1
  AND state = 'pending'
RETURNING id, game_id, initiator_id, state, started_at, ended_at
`

func (q *Queries) ActivateVoiceSession(ctx context.Context, id pgtype.UUID) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, activateVoiceSession, id)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.InitiatorID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createVoiceSession = `-- name: CreateVoiceSession :one
INSERT INTO voice_sessions (game_id, initiator_id)
VALUES ($1, $2)
RETURNING id, game_id, initiator_id, state, started_at, ended_at
`

type CreateVoiceSessionParams struct {
	GameID      pgtype.UUID `json:"game_id"`
	InitiatorID pgtype.UUID `json:"initiator_id"`
}

func (q *Queries) CreateVoiceSession(ctx context.Context, arg CreateVoiceSessionParams) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, createVoiceSession, arg.GameID, arg.InitiatorID)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.InitiatorID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const endVoiceSession = `-- name: EndVoiceSession :one
UPDATE voice_sessions
SET
    state    = 'ended',
    ended_at = NOW()
WHERE id = $1
  AND state != 'ended'
RETURNING id, game_id, initiator_id, state, started_at, ended_at
`

func (q *Queries) EndVoiceSession(ctx context.Context, id pgtype.UUID) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, endVoiceSession, id)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.InitiatorID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getActiveVoiceSessionByGameID = `-- name: GetActiveVoiceSessionByGameID :one
SELECT id, game_id, initiator_id, state, started_at, ended_at FROM voice_sessions
WHERE game_id = $1
  AND state IN ('pending', 'active')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveVoiceSessionByGameID(ctx context.Context, gameID pgtype.UUID) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, getActiveVoiceSessionByGameID, gameID)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.InitiatorID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVoiceSessionByID = `-- name: GetVoiceSessionByID :one
SELECT id, game_id, initiator_id, state, started_at, ended_at FROM voice_sessions
WHERE id = $1
`

func (q *Queries) GetVoiceSessionByID(ctx context.Context, id pgtype.UUID) (VoiceSession, error) {
	row := q.db.QueryRow(ctx, getVoiceSessionByID, id)
	var i VoiceSession
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.InitiatorID,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getVoiceSessionsByGameID = `-- name: GetVoiceSessionsByGameID :many
SELECT id, game_id, initiator_id, state, started_at, ended_at FROM voice_sessions
WHERE game_id = $1
ORDER BY started_at DESC
`

func (q *Queries) GetVoiceSessionsByGameID(ctx context.Context, gameID pgtype.UUID) ([]VoiceSession, error) {
	rows, err := q.db.Query(ctx, getVoiceSessionsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceSession{}
	for rows.Next() {
		var i VoiceSession
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.InitiatorID,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
