// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Glenn444/golang-chess/internal/db (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination internal/db/mock/store.go github.com/Glenn444/golang-chess/internal/db Store
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	db "github.com/Glenn444/golang-chess/internal/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockStore) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockStoreMockRecorder) ActivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockStore)(nil).ActivateUser), ctx, id)
}

// ActivateVoiceSession mocks base method.
func (m *MockStore) ActivateVoiceSession(ctx context.Context, id pgtype.UUID) (db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateVoiceSession", ctx, id)
	ret0, _ := ret[0].(db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateVoiceSession indicates an expected call of ActivateVoiceSession.
func (mr *MockStoreMockRecorder) ActivateVoiceSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateVoiceSession", reflect.TypeOf((*MockStore)(nil).ActivateVoiceSession), ctx, id)
}

// ConfirmEmail mocks base method.
func (m *MockStore) ConfirmEmail(ctx context.Context, id pgtype.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmail", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmEmail indicates an expected call of ConfirmEmail.
func (mr *MockStoreMockRecorder) ConfirmEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmail", reflect.TypeOf((*MockStore)(nil).ConfirmEmail), ctx, id)
}

// CountMovesByGameID mocks base method.
func (m *MockStore) CountMovesByGameID(ctx context.Context, gameID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMovesByGameID", ctx, gameID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMovesByGameID indicates an expected call of CountMovesByGameID.
func (mr *MockStoreMockRecorder) CountMovesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMovesByGameID", reflect.TypeOf((*MockStore)(nil).CountMovesByGameID), ctx, gameID)
}

// CountRecentOTPsForUser mocks base method.
func (m *MockStore) CountRecentOTPsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentOTPsForUser", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentOTPsForUser indicates an expected call of CountRecentOTPsForUser.
func (mr *MockStoreMockRecorder) CountRecentOTPsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentOTPsForUser", reflect.TypeOf((*MockStore)(nil).CountRecentOTPsForUser), ctx, userID)
}

// CreateChatMessage mocks base method.
func (m *MockStore) CreateChatMessage(ctx context.Context, arg db.CreateChatMessageParams) (db.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatMessage", ctx, arg)
	ret0, _ := ret[0].(db.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatMessage indicates an expected call of CreateChatMessage.
func (mr *MockStoreMockRecorder) CreateChatMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatMessage", reflect.TypeOf((*MockStore)(nil).CreateChatMessage), ctx, arg)
}

// CreateEmailOTP mocks base method.
func (m *MockStore) CreateEmailOTP(ctx context.Context, arg db.CreateEmailOTPParams) (db.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailOTP", ctx, arg)
	ret0, _ := ret[0].(db.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmailOTP indicates an expected call of CreateEmailOTP.
func (mr *MockStoreMockRecorder) CreateEmailOTP(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailOTP", reflect.TypeOf((*MockStore)(nil).CreateEmailOTP), ctx, arg)
}

// CreateGameAsBlack mocks base method.
func (m *MockStore) CreateGameAsBlack(ctx context.Context, blackPlayerID pgtype.UUID) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGameAsBlack", ctx, blackPlayerID)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGameAsBlack indicates an expected call of CreateGameAsBlack.
func (mr *MockStoreMockRecorder) CreateGameAsBlack(ctx, blackPlayerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGameAsBlack", reflect.TypeOf((*MockStore)(nil).CreateGameAsBlack), ctx, blackPlayerID)
}

// CreateGameAsWhite mocks base method.
func (m *MockStore) CreateGameAsWhite(ctx context.Context, whitePlayerID pgtype.UUID) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGameAsWhite", ctx, whitePlayerID)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGameAsWhite indicates an expected call of CreateGameAsWhite.
func (mr *MockStoreMockRecorder) CreateGameAsWhite(ctx, whitePlayerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGameAsWhite", reflect.TypeOf((*MockStore)(nil).CreateGameAsWhite), ctx, whitePlayerID)
}

// CreateMove mocks base method.
func (m *MockStore) CreateMove(ctx context.Context, arg db.CreateMoveParams) (db.GameMove, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMove", ctx, arg)
	ret0, _ := ret[0].(db.GameMove)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMove indicates an expected call of CreateMove.
func (mr *MockStoreMockRecorder) CreateMove(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMove", reflect.TypeOf((*MockStore)(nil).CreateMove), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// CreateVoiceSession mocks base method.
func (m *MockStore) CreateVoiceSession(ctx context.Context, arg db.CreateVoiceSessionParams) (db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVoiceSession", ctx, arg)
	ret0, _ := ret[0].(db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVoiceSession indicates an expected call of CreateVoiceSession.
func (mr *MockStoreMockRecorder) CreateVoiceSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVoiceSession", reflect.TypeOf((*MockStore)(nil).CreateVoiceSession), ctx, arg)
}

// DeactivateUser mocks base method.
func (m *MockStore) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockStoreMockRecorder) DeactivateUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockStore)(nil).DeactivateUser), ctx, id)
}

// DeleteChatMessagesByGameID mocks base method.
func (m *MockStore) DeleteChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChatMessagesByGameID", ctx, gameID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChatMessagesByGameID indicates an expected call of DeleteChatMessagesByGameID.
func (mr *MockStoreMockRecorder) DeleteChatMessagesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChatMessagesByGameID", reflect.TypeOf((*MockStore)(nil).DeleteChatMessagesByGameID), ctx, gameID)
}

// DeleteExpiredOTPs mocks base method.
func (m *MockStore) DeleteExpiredOTPs(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredOTPs", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredOTPs indicates an expected call of DeleteExpiredOTPs.
func (mr *MockStoreMockRecorder) DeleteExpiredOTPs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredOTPs", reflect.TypeOf((*MockStore)(nil).DeleteExpiredOTPs), ctx)
}

// DeleteExpiredSessions mocks base method.
func (m *MockStore) DeleteExpiredSessions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSessions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredSessions indicates an expected call of DeleteExpiredSessions.
func (mr *MockStoreMockRecorder) DeleteExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSessions", reflect.TypeOf((*MockStore)(nil).DeleteExpiredSessions), ctx)
}

// DeleteGame mocks base method.
func (m *MockStore) DeleteGame(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGame", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGame indicates an expected call of DeleteGame.
func (mr *MockStoreMockRecorder) DeleteGame(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGame", reflect.TypeOf((*MockStore)(nil).DeleteGame), ctx, id)
}

// DeleteMovesByGameID mocks base method.
func (m *MockStore) DeleteMovesByGameID(ctx context.Context, gameID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovesByGameID", ctx, gameID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMovesByGameID indicates an expected call of DeleteMovesByGameID.
func (mr *MockStoreMockRecorder) DeleteMovesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovesByGameID", reflect.TypeOf((*MockStore)(nil).DeleteMovesByGameID), ctx, gameID)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// EndVoiceSession mocks base method.
func (m *MockStore) EndVoiceSession(ctx context.Context, id pgtype.UUID) (db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndVoiceSession", ctx, id)
	ret0, _ := ret[0].(db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndVoiceSession indicates an expected call of EndVoiceSession.
func (mr *MockStoreMockRecorder) EndVoiceSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVoiceSession", reflect.TypeOf((*MockStore)(nil).EndVoiceSession), ctx, id)
}

// GetActiveVoiceSessionByGameID mocks base method.
func (m *MockStore) GetActiveVoiceSessionByGameID(ctx context.Context, gameID pgtype.UUID) (db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVoiceSessionByGameID", ctx, gameID)
	ret0, _ := ret[0].(db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVoiceSessionByGameID indicates an expected call of GetActiveVoiceSessionByGameID.
func (mr *MockStoreMockRecorder) GetActiveVoiceSessionByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVoiceSessionByGameID", reflect.TypeOf((*MockStore)(nil).GetActiveVoiceSessionByGameID), ctx, gameID)
}

// GetChatMessagesByGameID mocks base method.
func (m *MockStore) GetChatMessagesByGameID(ctx context.Context, gameID pgtype.UUID) ([]db.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessagesByGameID", ctx, gameID)
	ret0, _ := ret[0].([]db.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessagesByGameID indicates an expected call of GetChatMessagesByGameID.
func (mr *MockStoreMockRecorder) GetChatMessagesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessagesByGameID", reflect.TypeOf((*MockStore)(nil).GetChatMessagesByGameID), ctx, gameID)
}

// GetChatMessagesByGameIDPaginated mocks base method.
func (m *MockStore) GetChatMessagesByGameIDPaginated(ctx context.Context, arg db.GetChatMessagesByGameIDPaginatedParams) ([]db.ChatMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatMessagesByGameIDPaginated", ctx, arg)
	ret0, _ := ret[0].([]db.ChatMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatMessagesByGameIDPaginated indicates an expected call of GetChatMessagesByGameIDPaginated.
func (mr *MockStoreMockRecorder) GetChatMessagesByGameIDPaginated(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatMessagesByGameIDPaginated", reflect.TypeOf((*MockStore)(nil).GetChatMessagesByGameIDPaginated), ctx, arg)
}

// GetGameByID mocks base method.
func (m *MockStore) GetGameByID(ctx context.Context, id pgtype.UUID) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameByID", ctx, id)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameByID indicates an expected call of GetGameByID.
func (mr *MockStoreMockRecorder) GetGameByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameByID", reflect.TypeOf((*MockStore)(nil).GetGameByID), ctx, id)
}

// GetGamesByPlayerID mocks base method.
func (m *MockStore) GetGamesByPlayerID(ctx context.Context, whitePlayerID pgtype.UUID) ([]db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGamesByPlayerID", ctx, whitePlayerID)
	ret0, _ := ret[0].([]db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGamesByPlayerID indicates an expected call of GetGamesByPlayerID.
func (mr *MockStoreMockRecorder) GetGamesByPlayerID(ctx, whitePlayerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGamesByPlayerID", reflect.TypeOf((*MockStore)(nil).GetGamesByPlayerID), ctx, whitePlayerID)
}

// GetLastMoveByGameID mocks base method.
func (m *MockStore) GetLastMoveByGameID(ctx context.Context, gameID pgtype.UUID) (db.GameMove, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastMoveByGameID", ctx, gameID)
	ret0, _ := ret[0].(db.GameMove)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMoveByGameID indicates an expected call of GetLastMoveByGameID.
func (mr *MockStoreMockRecorder) GetLastMoveByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMoveByGameID", reflect.TypeOf((*MockStore)(nil).GetLastMoveByGameID), ctx, gameID)
}

// GetMovesByGameID mocks base method.
func (m *MockStore) GetMovesByGameID(ctx context.Context, gameID pgtype.UUID) ([]db.GameMove, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovesByGameID", ctx, gameID)
	ret0, _ := ret[0].([]db.GameMove)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovesByGameID indicates an expected call of GetMovesByGameID.
func (mr *MockStoreMockRecorder) GetMovesByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovesByGameID", reflect.TypeOf((*MockStore)(nil).GetMovesByGameID), ctx, gameID)
}

// GetSessionByRefreshToken mocks base method.
func (m *MockStore) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshToken indicates an expected call of GetSessionByRefreshToken.
func (mr *MockStoreMockRecorder) GetSessionByRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshToken", reflect.TypeOf((*MockStore)(nil).GetSessionByRefreshToken), ctx, refreshToken)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(ctx context.Context, id pgtype.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// GetValidOTP mocks base method.
func (m *MockStore) GetValidOTP(ctx context.Context, userID pgtype.UUID) (db.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidOTP", ctx, userID)
	ret0, _ := ret[0].(db.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidOTP indicates an expected call of GetValidOTP.
func (mr *MockStoreMockRecorder) GetValidOTP(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidOTP", reflect.TypeOf((*MockStore)(nil).GetValidOTP), ctx, userID)
}

// GetVoiceSessionByID mocks base method.
func (m *MockStore) GetVoiceSessionByID(ctx context.Context, id pgtype.UUID) (db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVoiceSessionByID", ctx, id)
	ret0, _ := ret[0].(db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVoiceSessionByID indicates an expected call of GetVoiceSessionByID.
func (mr *MockStoreMockRecorder) GetVoiceSessionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVoiceSessionByID", reflect.TypeOf((*MockStore)(nil).GetVoiceSessionByID), ctx, id)
}

// GetVoiceSessionsByGameID mocks base method.
func (m *MockStore) GetVoiceSessionsByGameID(ctx context.Context, gameID pgtype.UUID) ([]db.VoiceSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVoiceSessionsByGameID", ctx, gameID)
	ret0, _ := ret[0].([]db.VoiceSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVoiceSessionsByGameID indicates an expected call of GetVoiceSessionsByGameID.
func (mr *MockStoreMockRecorder) GetVoiceSessionsByGameID(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVoiceSessionsByGameID", reflect.TypeOf((*MockStore)(nil).GetVoiceSessionsByGameID), ctx, gameID)
}

// IncrementOTPAttempts mocks base method.
func (m *MockStore) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) (db.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOTPAttempts", ctx, id)
	ret0, _ := ret[0].(db.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementOTPAttempts indicates an expected call of IncrementOTPAttempts.
func (mr *MockStoreMockRecorder) IncrementOTPAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOTPAttempts", reflect.TypeOf((*MockStore)(nil).IncrementOTPAttempts), ctx, id)
}

// InvalidateUserOTPs mocks base method.
func (m *MockStore) InvalidateUserOTPs(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserOTPs", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserOTPs indicates an expected call of InvalidateUserOTPs.
func (mr *MockStoreMockRecorder) InvalidateUserOTPs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserOTPs", reflect.TypeOf((*MockStore)(nil).InvalidateUserOTPs), ctx, userID)
}

// JoinGameAsBlack mocks base method.
func (m *MockStore) JoinGameAsBlack(ctx context.Context, arg db.JoinGameAsBlackParams) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGameAsBlack", ctx, arg)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinGameAsBlack indicates an expected call of JoinGameAsBlack.
func (mr *MockStoreMockRecorder) JoinGameAsBlack(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGameAsBlack", reflect.TypeOf((*MockStore)(nil).JoinGameAsBlack), ctx, arg)
}

// JoinGameAsWhite mocks base method.
func (m *MockStore) JoinGameAsWhite(ctx context.Context, arg db.JoinGameAsWhiteParams) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGameAsWhite", ctx, arg)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinGameAsWhite indicates an expected call of JoinGameAsWhite.
func (mr *MockStoreMockRecorder) JoinGameAsWhite(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGameAsWhite", reflect.TypeOf((*MockStore)(nil).JoinGameAsWhite), ctx, arg)
}

// ListWaitingGames mocks base method.
func (m *MockStore) ListWaitingGames(ctx context.Context) ([]db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWaitingGames", ctx)
	ret0, _ := ret[0].([]db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWaitingGames indicates an expected call of ListWaitingGames.
func (mr *MockStoreMockRecorder) ListWaitingGames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWaitingGames", reflect.TypeOf((*MockStore)(nil).ListWaitingGames), ctx)
}

// MarkOTPUsed mocks base method.
func (m *MockStore) MarkOTPUsed(ctx context.Context, id pgtype.UUID) (db.EmailOtp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOTPUsed", ctx, id)
	ret0, _ := ret[0].(db.EmailOtp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOTPUsed indicates an expected call of MarkOTPUsed.
func (mr *MockStoreMockRecorder) MarkOTPUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOTPUsed", reflect.TypeOf((*MockStore)(nil).MarkOTPUsed), ctx, id)
}

// RevokeAllUserSessions mocks base method.
func (m *MockStore) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserSessions indicates an expected call of RevokeAllUserSessions.
func (mr *MockStoreMockRecorder) RevokeAllUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessions", reflect.TypeOf((*MockStore)(nil).RevokeAllUserSessions), ctx, userID)
}

// RevokeSession mocks base method.
func (m *MockStore) RevokeSession(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockStoreMockRecorder) RevokeSession(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockStore)(nil).RevokeSession), ctx, refreshToken)
}

// UpdateGameState mocks base method.
func (m *MockStore) UpdateGameState(ctx context.Context, arg db.UpdateGameStateParams) (db.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGameState", ctx, arg)
	ret0, _ := ret[0].(db.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGameState indicates an expected call of UpdateGameState.
func (mr *MockStoreMockRecorder) UpdateGameState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGameState", reflect.TypeOf((*MockStore)(nil).UpdateGameState), ctx, arg)
}

// UpdateLastLogin mocks base method.
func (m *MockStore) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockStoreMockRecorder) UpdateLastLogin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockStore)(nil).UpdateLastLogin), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(ctx context.Context, arg db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, arg)
}

// UsernameExists mocks base method.
func (m *MockStore) UsernameExists(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsernameExists", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsernameExists indicates an expected call of UsernameExists.
func (mr *MockStoreMockRecorder) UsernameExists(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsernameExists", reflect.TypeOf((*MockStore)(nil).UsernameExists), ctx, username)
}
