// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_moves.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMovesByGameID = `-- name: CountMovesByGameID :one
SELECT COUNT(*) FROM game_moves
WHERE game_id = $1
`

func (q *Queries) CountMovesByGameID(ctx context.Context, gameID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMovesByGameID, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMove = `-- name: CreateMove :one
INSERT INTO game_moves (game_id, player_id, player_color, move_notation, move_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, player_id, player_color, move_notation, move_number, created_at
`

type CreateMoveParams struct {
	GameID       pgtype.UUID `json:"game_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PlayerColor  PlayerColor `json:"player_color"`
	MoveNotation string      `json:"move_notation"`
	MoveNumber   int32       `json:"move_number"`
}

func (q *Queries) CreateMove(ctx context.Context, arg CreateMoveParams) (GameMove, error) {
	row := q.db.QueryRow(ctx, createMove,
		arg.GameID,
		arg.PlayerID,
		arg.PlayerColor,
		arg.MoveNotation,
		arg.MoveNumber,
	)
	var i GameMove
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.PlayerColor,
		&i.MoveNotation,
		&i.MoveNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMovesByGameID = `-- name: DeleteMovesByGameID :exec
DELETE FROM game_moves
WHERE game_id = $1
`

func (q *Queries) DeleteMovesByGameID(ctx context.Context, gameID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovesByGameID, gameID)
	return err
}

const getLastMoveByGameID = `-- name: GetLastMoveByGameID :one
SELECT id, game_id, player_id, player_color, move_notation, move_number, created_at FROM game_moves
WHERE game_id = $1
ORDER BY move_number DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLastMoveByGameID(ctx context.Context, gameID pgtype.UUID) (GameMove, error) {
	row := q.db.QueryRow(ctx, getLastMoveByGameID, gameID)
	var i GameMove
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.PlayerColor,
		&i.MoveNotation,
		&i.MoveNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getMovesByGameID = `-- name: GetMovesByGameID :many
SELECT id, game_id, player_id, player_color, move_notation, move_number, created_at FROM game_moves
WHERE game_id = $1
ORDER BY move_number ASC, created_at ASC
`

func (q *Queries) GetMovesByGameID(ctx context.Context, gameID pgtype.UUID) ([]GameMove, error) {
	rows, err := q.db.Query(ctx, getMovesByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameMove{}
	for rows.Next() {
		var i GameMove
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.PlayerColor,
			&i.MoveNotation,
			&i.MoveNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
