// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBoardState() {
  return window['go']['main']['App']['GetBoardState']();
}

export function GetCurrentPlayer() {
  return window['go']['main']['App']['GetCurrentPlayer']();
}

export function MakeMove(arg1) {
  return window['go']['main']['App']['MakeMove'](arg1);
}
