// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {board} from '../models';

export function GetBoardState():Promise<board.GameState>;

export function GetCurrentPlayer():Promise<string>;

export function GetLegalSquares(arg1:number,arg2:number):Promise<Array<string>>;

export function GetPieceString(arg1:number,arg2:number):Promise<string>;

export function MakeMove(arg1:string):Promise<board.GameState>;
