// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {board} from '../models';

export function GetBoardState():Promise<Array<any>>;

export function GetCurrentPlayer():Promise<string>;

export function MakeMove(arg1:string):Promise<board.GameState>;
